name: Publish next Package

on:
  push:
    tags:
      - v*-beta*
      - v*-alpha*
      - v*-next*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install --frozen-lockfile
      - run: npm run build:clean
      - run: npm run test
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
